import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "You Can WIN",
    author: "Shiv Khera",
    price: "5000",
    image: "https://m.media-amazon.com/images/I/41y2KJ+kDLL._SY344_BO1,204,203,200_.jpg",
    categoryName: "non-fiction",
    rating: "4.2",
  },
  {
    _id: uuid(),
    title: "Ghosts in the Dark Silence",
    author: "Anita Krishan",
    price: "3000",
    image: "https://m.media-amazon.com/images/I/51ilPjmFjeL._SY498_BO1,204,203,200_.jpg",
    categoryName: "horror",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    price: "1000",
    image: "https://m.media-amazon.com/images/I/41CqlzJS-NL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    categoryName: "fiction",
    rating: "2",
  },
  {
    _id: uuid(),
    title: "Zero To One",
    author: "Peter Thiel",
    price: "2000",
    image: "https://m.media-amazon.com/images/I/513KQR73LdL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    categoryName: "fiction",
    rating: "4.8",
  },
  {
    _id: uuid(),
    title: "One Indian Girl",
    author: "Chetan Bhagat",
    price: "3000",
    image: "https://m.media-amazon.com/images/I/41pAG-O6FlL._SX361_BO1,204,203,200_.jpg",
    categoryName: "fiction",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "IKIGAI",
    author: "Hector Garcia",
    price: "1500",
    image: "https://m.media-amazon.com/images/I/41k8aHbVSBL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    categoryName: "non-fiction",
    rating: "3.5",
  },
  {
    _id: uuid(),
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyoski",
    price: "500",
    image: "https://m.media-amazon.com/images/I/51Hfv2MfNGL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    categoryName: "non-fiction",
    rating: "2.5",
  },
  {
    _id: uuid(),
    title: "Man's Search For Meaning",
    author: "Franky Viktor",
    price: "2500",
    image: "https://m.media-amazon.com/images/I/41ZgK6u73qL._SX313_BO1,204,203,200_.jpg",
    categoryName: "non-fiction",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "Frankenstein",
    author: "Mary Shelley",
    price: "1500",
    image: "https://m.media-amazon.com/images/I/51Wtzp-kSkL._SX198_BO1,204,203,200_QL40_FMwebp_.jpg",
    categoryName: "horror",
    rating: "3.5",
  },
  {
    _id: uuid(),
    title: "John Dies At The End",
    author: "David Wong",
    price: "4000",
    image: "https://m.media-amazon.com/images/I/513sCUX27NL._SX331_BO1,204,203,200_.jpg",
    categoryName: "horror",
    rating: "1",
  },
  {
    _id: uuid(),
    title: "The Missing",
    author: "Sarah Langan",
    price: "1000",
    image: "https://m.media-amazon.com/images/I/41qzmZre-fL._SX321_BO1,204,203,200_.jpg",
    categoryName: "horror",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "The Walking",
    author: "Bentley Little",
    price: "2000",
    image: "https://m.media-amazon.com/images/I/51hK2TZ6zBL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    categoryName: "horror",
    rating: "4",
  },
];
